' LoneClass.J()

@startuml
activate LoneClass

LoneClass -> LoneClass : A()
activate LoneClass
deactivate LoneClass

LoneClass -> LoneClass : B()
activate LoneClass
deactivate LoneClass

deactivate LoneClass
@enduml