' LoneClass.W()

@startuml
activate LoneClass

LoneClass -> FriendlyClass : Method04()
activate FriendlyClass
deactivate FriendlyClass

loop i < 10 
    LoneClass -> FriendlyClass : Method05()
    activate FriendlyClass
    deactivate FriendlyClass
end
 
LoneClass -> FriendlyClass :Method06()
activate FriendlyClass
deactivate FriendlyClass

deactivate LoneClass
@enduml